export const subCategoryNames: Record<string, string> = {
  // Computer Science
  "AI": "Artificial Intelligence",
  "AR": "Hardware Architecture",
  "CC": "Computational Complexity",
  "CE": "Computational Engineering & Science",
  "CL": "Computation & Language",
  "CR": "Cryptography & Security",
  "CY": "Computers & Society",
  "ComputerScience::CG": "Computational Geometry",
  "ComputerScience::CV": "Computer Vision & Pattern Recognition",
  "ComputerScience::GR": "Graphics",
  "ComputerScience::GT": "Computer Science & Game Theory",
  "ComputerScience::LO": "Logic in Computer Science",
  "ComputerScience::SI": "Social & Information Networks",
  "DB": "Databases",
  "DC": "Distributed & Parallel Computing",
  "DM": "Discrete Mathematics",
  "DS": "Data Structures & Algorithms",
  "ET": "Emerging Technologies",
  "FL": "Formal Languages & Automata",
  "HC": "Human-Computer Interaction",
  "IR": "Information Retrieval",
  "IT": "Information Theory",
  "LG": "Machine Learning",
  "MA": "Multiagent Systems",
  "MM": "Multimedia",
  "MS": "Mathematical Software",
  "NE": "Neural & Evolutionary Computing",
  "NI": "Networking & Internet Architecture",
  "OS": "Operating Systems",
  "PF": "Performance",
  "PL": "Programming Languages",
  "RO": "Robotics",
  "SD": "Sound",
  "SE": "Software Engineering",

  // Economics
  "EM": "Econometrics",
  "Economics::GN": "General Economics",
  "TH": "Theoretical Economics",

  // Electrical Engineering
  "AS": "Audio & Speech Processing",
  "ElectricalEngineering::SP": "Signal Processing",
  "IV": "Image & Video Processing",
  "SY": "Systems & Control",

  // Mathematics
  "AC": "Commutative Algebra",
  "AG": "Algebraic Geometry",
  "AT": "Algebraic Topology",
  "CA": "Classical Analysis & ODEs",
  "CT": "Category Theory",
  "DG": "Differential Geometry",
  "FA": "Functional Analysis",
  "GM": "General Mathematics",
  "HO": "History & Overview",
  "KT": "K-Theory & Homology",
  "Mathematics::AP": "Analysis of PDEs",
  "Mathematics::CO": "Combinatorics",
  "Mathematics::CV": "Complex Variables",
  "Mathematics::GN": "General Topology",
  "Mathematics::GR": "Group Theory",
  "Mathematics::GT": "Geometric Topology",
  "Mathematics::LO": "Logic",
  "Mathematics::PR": "Probability",
  "Mathematics::SP": "Spectral Theory",
  "Mathematics::ST": "Statistics Theory",
  "NA": "Numerical Analysis",
  "NT": "Number Theory",
  "OA": "Operator Algebras",
  "OC": "Optimization & Control",
  "QA": "Quantum Algebra",
  "RA": "Rings & Algebras",
  "RT": "Representation Theory",
  "SG": "Symplectic Geometry",

  // Physics
  "AO": "Atmospheric & Oceanic Physics",
  "CD": "Chaotic Dynamics",
  "EP": "Physics Education",
  "GA": "Galaxies",
  "General": "General Physics",
  "HE": "High Energy Astrophysical Phenomena",
  "IM": "Instrumentation & Methods",
  "Physics::CG": "Computational Physics",
  "Physics::CO": "Cosmology & Nongalactic Astrophysics",
  "Physics::SI": "Solar & Stellar Astrophysics",
  "acc-ph": "Accelerator Physics",
  "ao-ph": "Atmospheric & Oceanic Physics",
  "atom-ph": "Atomic Physics",
  "bio-ph": "Biological Physics",
  "chem-ph": "Chemical Physics",
  "comp-ph": "Computational Physics",
  "data-an": "Data Analysis & Statistics",
  "dis-nn": "Disordered Systems & Neural Networks",
  "flu-dyn": "Fluid Dynamics",
  "ins-det": "Instrumentation & Detectors",
  "mes-hall": "Mesoscale & Nanoscale Physics",
  "mtrl-sci": "Materials Science",
  "optics": "Optics",
  "other": "Other",
  "plasm-ph": "Plasma Physics",
  "quant-gas": "Quantum Gases",
  "soc-ph": "Physics & Society",
  "soft": "Soft Condensed Matter",
  "space-ph": "Space Physics",
  "stat-mech": "Statistical Mechanics",
  "str-el": "Strongly Correlated Electrons",

  // Quantitative Biology
  "BM": "Biomolecules",
  "MN": "Neurons & Cognition",
  "NC": "Neurons & Cognition",
  "PE": "Populations & Evolution",
  "QM": "Quantitative Methods",
  "QuantitativeBiology::GN": "Genomics",

  // Quantitative Finance
  "CP": "Computational Finance",
  "MF": "Mathematical Finance",
  "PM": "Portfolio Management",
  "QuantitativeFinance::PR": "Pricing of Securities",
  "QuantitativeFinance::ST": "Statistical Finance",
  "RM": "Risk Management",

  // Statistics
  "ME": "Methodology",
  "ML": "Machine Learning",
  "OT": "Other Statistics",
  "Statistics::AP": "Applications",
  "Statistics::CO": "Computation",
}
