import { useState } from "react"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import PaperForm from "./components/PaperForm"
import ResultsPanel from "./components/ResultsPanel"
import { PredictResponse } from "./api/client"

const queryClient = new QueryClient()

export default function App() {
  const [result, setResult] = useState<PredictResponse | null>(null)

  return (
    <QueryClientProvider client={queryClient}>
      <div className="min-h-screen flex flex-col" style={{ backgroundImage: 'url(/Blue.jpg)', backgroundSize: 'cover', backgroundPosition: 'center', backgroundAttachment: 'fixed' }}>
        {/* Top bar with emblem, title, and college info */}
        <div className="border-b border-gray-200 px-6 py-4" style={{ backgroundColor: '#EFEFD0' }}>
          <div className="max-w-6xl mx-auto flex items-center justify-between">
            {/* Left: Emblem */}
            <div className="flex-shrink-0">
              <img 
                src="/Emblem.png" 
                alt="College Emblem" 
                className="h-14"
              />
            </div>

            {/* Center: Title */}
            <div className="flex-1 text-center px-8">
              <h1 className="text-3xl font-bold text-gray-900">
                ArXiv Paper Classifier
              </h1>
            </div>

            {/* Right: College info */}
            <div className="flex-shrink-0 text-right text-sm">
              <div className="font-semibold text-gray-900">RV College of Engineering</div>
              <div className="text-gray-600">Department of AIML</div>
            </div>
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 flex flex-col items-center justify-center px-4 py-12">
          <div className="w-full max-w-2xl">
            <p className="text-center mb-8" style={{ color: '#EFEFD0' }}>
              Paste a paper's title and abstract to classify it into an ArXiv category
            </p>
            <div className="rounded-2xl shadow-md p-8" style={{ backgroundColor: '#EFEFD0' }}>
              {result
                ? <ResultsPanel result={result} onReset={() => setResult(null)} />
                : <PaperForm onResult={setResult} />
              }
            </div>

            {/* Disclaimer */}
            <div className="mt-6 text-center">
              <p className="text-xs" style={{ color: '#EFEFD0' }}>
                ⚠️ Disclaimer: Results are generated by a machine learning model and may not always be accurate. This tool is intended for academic purposes only.
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="py-4">
          <p className="text-xs text-center" style={{ color: '#EFEFD0' }}>
            Developed by Navyasri Mahitha Pulipati, Shreya Mohan and Shravyaa S
          </p>
        </div>
      </div>
    </QueryClientProvider>
  )
}
